name: card_games
description: "Poker Gambit - A high-stakes strategic card game with AI opponent."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Game & Animation
  flame: ^1.11.0         # Jika ingin performa game loop murni
  google_fonts: ^6.1.0   # Tipografi game yang keren
  flutter_svg: ^2.0.10+1 # Untuk aset kartu vektor agar tidak pecah
  audioplayers: ^5.2.1   # Sound effects
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  fake_async: ^1.3.1
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cards/
    - assets/audio/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/poker-gambit.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/poker-gambit.png"
  macos:
    generate: true
    image_path: "assets/images/poker-gambit.png"
