name: card_games
description: "A strategic poker card game called Poker Gambit."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Game & Animation
  flame: ^1.11.0         # Jika ingin performa game loop murni
  google_fonts: ^6.1.0   # Tipografi game yang keren
  flutter_svg: ^2.0.10+1 # Untuk aset kartu vektor agar tidak pecah
  audioplayers: ^5.2.1   # Sound effects
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  fake_async: ^1.3.1
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/cards/
    - assets/audio/
    - .env
