// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_WEB', fallback: ''),
    messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
    authDomain: dotenv.get('FIREBASE_AUTH_DOMAIN', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
    measurementId: dotenv.get('FIREBASE_MEASUREMENT_ID_WEB', fallback: ''),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_ANDROID', fallback: ''),
    messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_IOS', fallback: ''),
    messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
    androidClientId:
        dotenv.get('GOOGLE_ANDROID_CLIENT_ID', fallback: ''),
    iosClientId:
        dotenv.get('GOOGLE_IOS_CLIENT_ID', fallback: ''),
    iosBundleId: dotenv.get('IOS_BUNDLE_ID', fallback: ''),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_MACOS', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_IOS', fallback: ''),
    messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
    androidClientId:
        dotenv.get('GOOGLE_ANDROID_CLIENT_ID', fallback: ''),
    iosClientId:
        dotenv.get('GOOGLE_IOS_CLIENT_ID', fallback: ''),
    iosBundleId: dotenv.get('IOS_BUNDLE_ID', fallback: ''),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WINDOWS', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_WINDOWS', fallback: ''),
    messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
    authDomain: dotenv.get('FIREBASE_AUTH_DOMAIN', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
    measurementId: dotenv.get('FIREBASE_MEASUREMENT_ID_WINDOWS', fallback: ''),
  );
}
