// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfRWw31sAbb6vFFt8Gi8h-Fqzw4dlRwI',
    appId: '1:740482939505:web:d0714ad5121b725ea179d0',
    messagingSenderId: '740482939505',
    projectId: 'poker-gambit',
    authDomain: 'poker-gambit.firebaseapp.com',
    storageBucket: 'poker-gambit.firebasestorage.app',
    measurementId: 'G-SKVMBLKS0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76zMvbPKkqzNmGUNho-ta4tvRH6-FJ-0',
    appId: '1:740482939505:android:4b237754c9ee13a2a179d0',
    messagingSenderId: '740482939505',
    projectId: 'poker-gambit',
    storageBucket: 'poker-gambit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0NXoz4rca1NKv7wCULVPehU8n5lytXM',
    appId: '1:740482939505:ios:7dd3e979c1d9e5dba179d0',
    messagingSenderId: '740482939505',
    projectId: 'poker-gambit',
    storageBucket: 'poker-gambit.firebasestorage.app',
    androidClientId: '740482939505-rde837sgpnpjgmjdg6q58ovocsdorq21.apps.googleusercontent.com',
    iosClientId: '740482939505-100nqphhn4bnqdum6no74hf4ii5mp8k0.apps.googleusercontent.com',
    iosBundleId: 'com.ssajud.cardgames.cardGames',
  );

}